CREATE OR REPLACE PROCEDURE INITIALIZE(NUM_INS NUMBER, CUSTOMERS_ARRAY ARRAY_TYPE, PRODUCTS_ARRAY ARRAY_TYPE) AS
BEGIN

  FOR TIMES IN 1..NUM_INS
  LOOP
    INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH, SURNAME) VALUES (SEQ_EMPLOYEE.NEXTVAL, 'Treballador '||SEQ_EMPLOYEE.CURRVAL, '01/01/2000', 'Cognom '||SEQ_EMPLOYEE.CURRVAL);
	INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID, SURNAME) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client '||SEQ_CUSTOMER.CURRVAL, SEQ_EMPLOYEE.CURRVAL, 'Cognom '||SEQ_CUSTOMER.CURRVAL);
	INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES (SEQ_PRODUCT.NEXTVAL, 'Producte '||SEQ_PRODUCT.CURRVAL, 'Descripció '||SEQ_PRODUCT.CURRVAL);
	INSERT INTO PRODUCT_CUSTOMER (PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (SEQ_PRODUCT.CURRVAL, SEQ_CUSTOMER.CURRVAL, SYSDATE);
  END LOOP;
END;
/

DECLARE
BEGIN
  INITIALIZE(3);
END;