DECLARE

  C_ID NUMBER(8);
  CURSOR EMPLEADOS_CUR IS
		SELECT *
		FROM EMPLOYEE;
	EMP_AUX EMPLOYEE%ROWTYPE;
  CURSOR CLIENT_CUR IS
    SELECT C.*
    FROM CUSTOMER C
      INNER JOIN EMPLOYEE E ON (E.ID=C.EMPLOYEE_ID);
  CLI_AUX CUSTOMER%ROWTYPE;
    
  
BEGIN
        
  OPEN EMPLEADOS_CUR;
    LOOP
      FETCH EMPLEADOS_CUR INTO EMP_AUX;
      EXIT WHEN EMPLEADOS_CUR%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('Nombre: ' || EMP_AUX.NAME || ' Apellido : ' || EMP_AUX.SURNAME);
      OPEN CLIENT_CUR;
        LOOP
          FETCH CLIENT_CUR INTO CLI_AUX;
          EXIT WHEN CLIENT_CUR%NOTFOUND;
          IF EMP_AUX.ID=CLI_AUX.EMPLOYEE_ID 
            THEN DBMS_OUTPUT.PUT_LINE('Cliente: ' || CLI_AUX.NAME);
          END IF;
        END LOOP;
      CLOSE CLIENT_CUR;
    END LOOP;
  CLOSE EMPLEADOS_CUR;
  
END;