SET SERVEROUTPUT ON
DECLARE

  CURSOR EMPLEADOS_CUR IS
		SELECT *
		FROM EMPLOYEE;
	EMP_AUX EMPLOYEE%ROWTYPE;
  CURSOR CLIENT_CUR (ID_EMP NUMBER) IS
    SELECT *
    FROM CUSTOMER
    WHERE EMPLOYEE_ID=ID_EMP;
  CLI_AUX CUSTOMER%ROWTYPE;
    
BEGIN  
  
  --Hacer lo mismo, pero con cursores con parámetros
        
  OPEN EMPLEADOS_CUR;
    LOOP
      FETCH EMPLEADOS_CUR INTO EMP_AUX;
      EXIT WHEN EMPLEADOS_CUR%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('Nombre: ' || EMP_AUX.NAME || ' Apellido : ' || EMP_AUX.SURNAME);
      OPEN CLIENT_CUR(EMP_AUX.ID);
        LOOP
          FETCH CLIENT_CUR INTO CLI_AUX;
          EXIT WHEN CLIENT_CUR%NOTFOUND;
          DBMS_OUTPUT.PUT_LINE('Cliente: ' || CLI_AUX.NAME);
        END LOOP;
      CLOSE CLIENT_CUR;
    END LOOP;
  CLOSE EMPLEADOS_CUR;
  
END;